name: Sync to Hugging Face Hub

on:
  push:
    branches: [main] # Or 'master' depending on your default branch name

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Install the Hugging Face CLI
          pip install huggingface_hub
          
          # 2. Upload the entire project using the HF CLI
          # This tool handles binary files perfectly without needing Git LFS manually
          huggingface-cli upload stargazer791/Customer-Retention-Engine . . --repo-type=space --token $HF_TOKEN --commit-message "Deploy via GitHub Action"