name: Sync to Hugging Face Hub

on:
  push:
    branches: [main] # Or 'master' depending on your default branch name

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Create a new temporary branch with no history
          git checkout --orphan latest-branch
          git add -A
          git commit -m "Deploy latest version"
          # Force push this single commit to Hugging Face
          git push --force https://stargazer791:$HF_TOKEN@huggingface.co/spaces/stargazer791/Customer-Retention-Engine latest-branch:main
